"""
Motherboard Core - Component map.

Declares every component of NT Commerce, its human-readable names, the API route
prefixes it owns, and the main MongoDB collections it touches. Importing this module
registers all components into the registry.
"""
from .registry import ModuleSpec, register

COMPONENTS: list[ModuleSpec] = [
    ModuleSpec("auth", "المصادقة والمستخدمون", "Auth & Users",
               ["/api/auth", "/api/users", "/api/permissions", "/api/two-factor"],
               ["users", "super_admins"]),
    ModuleSpec("products", "المنتجات", "Produits",
               ["/api/products", "/api/product-families", "/api/bulk-price", "/api/price-history",
                "/api/price-updates"],
               ["products", "product_families"]),
    ModuleSpec("sales", "المبيعات", "Ventes",
               ["/api/sales", "/api/pos", "/api/advanced-sales"],
               ["sales"]),
    ModuleSpec("purchases", "المشتريات", "Achats",
               ["/api/purchases"],
               ["purchases"]),
    ModuleSpec("customers", "الزبائن", "Clients",
               ["/api/customers", "/api/customer-families", "/api/customer-debts", "/api/blacklist",
                "/api/debt-reminders"],
               ["customers", "customer_families"]),
    ModuleSpec("suppliers", "الموردون", "Fournisseurs",
               ["/api/suppliers", "/api/supplier-families", "/api/supplier-tracking",
                "/api/supplier-debts"],
               ["suppliers", "supplier_families"]),
    ModuleSpec("inventory", "المخزون والمخازن", "Stock & Entrepôts",
               ["/api/warehouses", "/api/inventory", "/api/inventory-sessions", "/api/barcode",
                "/api/barcodes", "/api/stock-transfers", "/api/spare-parts", "/api/defective"],
               ["warehouses", "spare_parts"]),
    ModuleSpec("finance", "المالية والصندوق", "Finance & Caisse",
               ["/api/cash", "/api/cash-boxes", "/api/expenses", "/api/debts", "/api/payments",
                "/api/banking", "/api/currencies", "/api/wallet", "/api/transactions"],
               ["cash_boxes", "expenses", "debts", "transactions"]),
    ModuleSpec("accounting", "المحاسبة والضرائب", "Comptabilité & Taxes",
               ["/api/accounting", "/api/tax", "/api/invoices"],
               ["accounts", "journal_entries", "invoices", "tax_rates"]),
    ModuleSpec("repairs", "الصيانة", "Réparations",
               ["/api/repairs"],
               ["repair_tickets", "spare_parts"]),
    ModuleSpec("reports", "التقارير والإحصائيات", "Rapports & Stats",
               ["/api/reports", "/api/analytics", "/api/stats", "/api/dashboard", "/api/daily-sessions",
                "/api/auto-reports", "/api/collection-reports"],
               ["daily_reports", "daily_sessions"]),
    ModuleSpec("ai", "الذكاء الاصطناعي", "Intelligence Artificielle",
               ["/api/ai", "/api/smart-reports"],
               ["ai_insights", "chat_sessions", "agent_tasks"]),
    ModuleSpec("robots", "الروبوتات", "Robots",
               ["/api/robots"],
               []),
    ModuleSpec("notifications", "الإشعارات", "Notifications",
               ["/api/notifications", "/api/smart-notifications", "/api/push"],
               ["push_notifications", "notification_preferences"]),
    ModuleSpec("services", "الخدمات والولاء", "Services & Fidélité",
               ["/api/services", "/api/recharge", "/api/recharges", "/api/loyalty", "/api/sim",
                "/api/idoom"],
               ["mobile_recharge_tasks", "idoom_codes"]),
    ModuleSpec("store", "المتجر الإلكتروني", "Boutique en ligne",
               ["/api/store", "/api/online-store", "/api/woocommerce", "/api/shop", "/api/delivery"],
               []),
    ModuleSpec("integrations", "التكاملات", "Intégrations",
               ["/api/whatsapp", "/api/sms", "/api/stripe", "/api/sendgrid", "/api/email",
                "/api/yalidine", "/api/shipping", "/api/ocr", "/api/integrations", "/api/marketing",
                "/api/webhook"],
               []),
    ModuleSpec("employees", "الموظفون", "Employés",
               ["/api/employees", "/api/employee-alerts", "/api/agent"],
               ["employees"]),
    ModuleSpec("tasks", "المهام والدردشة", "Tâches & Chat",
               ["/api/tasks", "/api/task", "/api/chat", "/api/internal-chat"],
               ["tasks"]),
    ModuleSpec("search", "البحث", "Recherche",
               ["/api/search"],
               []),
    ModuleSpec("security", "الأمان", "Sécurité",
               ["/api/security", "/api/api-keys"],
               ["security_logs", "api_keys"]),
    ModuleSpec("backup", "النسخ الاحتياطي", "Sauvegardes",
               ["/api/backup", "/api/database", "/api/import-export", "/api/data-import-export",
                "/api/data", "/api/sync"],
               []),
    ModuleSpec("settings", "الإعدادات", "Paramètres",
               ["/api/settings", "/api/branding", "/api/printing", "/api/cache", "/api/performance",
                "/api/upload"],
               ["settings"]),
    ModuleSpec("saas", "إدارة المنصة", "Gestion SaaS",
               ["/api/saas", "/api/system-errors", "/api/hierarchy", "/api/system",
                "/api/system-updates", "/api/tenant"],
               ["plans", "tenants"]),
]

for _component in COMPONENTS:
    register(_component)
