# Default Permissions for each role
DEFAULT_PERMISSIONS = {
    "super_admin": {
        "dashboard": True,
        "pos": True,
        "products": {"view": True, "add": True, "edit": True, "delete": True, "price_change": True, "stock_adjust": True},
        "inventory": {"view": True, "add": True, "edit": True, "delete": True, "transfer": True, "count": True},
        "purchases": {"view": True, "add": True, "edit": True, "delete": True, "approve": True},
        "sales": {"view": True, "add": True, "edit": True, "delete": True, "refund": True, "discount": True},
        "customers": {"view": True, "add": True, "edit": True, "delete": True, "credit": True, "blacklist": True},
        "suppliers": {"view": True, "add": True, "edit": True, "delete": True, "payments": True},
        "employees": {"view": True, "add": True, "edit": True, "delete": True, "salary": True, "attendance": True},
        "debts": {"view": True, "add": True, "edit": True, "delete": True, "collect": True},
        "expenses": {"view": True, "add": True, "edit": True, "delete": True, "approve": True},
        "repairs": {"view": True, "add": True, "edit": True, "delete": True},
        "reports": {"sales": True, "inventory": True, "financial": True, "customers": True, "employees": True, "advanced": True},
        "settings": True,
        "users": {"view": True, "add": True, "edit": True, "delete": True, "permissions": True},
        "recharge": True,
        "api_keys": True,
        "factory_reset": True,
        "woocommerce": True,
        "delivery": True,
        "loyalty": True,
        "notifications": True,
        "maintenance": True,
        "saas_admin": True
    },
    "admin": {
        "dashboard": True,
        "pos": True,
        "products": {"view": True, "add": True, "edit": True, "delete": True, "price_change": True, "stock_adjust": True},
        "inventory": {"view": True, "add": True, "edit": True, "delete": True, "transfer": True, "count": True},
        "purchases": {"view": True, "add": True, "edit": True, "delete": True, "approve": True},
        "sales": {"view": True, "add": True, "edit": True, "delete": True, "refund": True, "discount": True},
        "customers": {"view": True, "add": True, "edit": True, "delete": True, "credit": True, "blacklist": True},
        "suppliers": {"view": True, "add": True, "edit": True, "delete": True, "payments": True},
        "employees": {"view": True, "add": True, "edit": True, "delete": True, "salary": True, "attendance": True},
        "debts": {"view": True, "add": True, "edit": True, "delete": True, "collect": True},
        "expenses": {"view": True, "add": True, "edit": True, "delete": True, "approve": True},
        "repairs": {"view": True, "add": True, "edit": True, "delete": True},
        "reports": {"sales": True, "inventory": True, "financial": True, "customers": True, "employees": True, "advanced": True},
        "settings": True,
        "users": {"view": True, "add": True, "edit": True, "delete": True, "permissions": True},
        "recharge": True,
        "api_keys": True,
        "factory_reset": True,
        "woocommerce": True,
        "delivery": True,
        "loyalty": True,
        "notifications": True,
        "maintenance": True
    },
    "manager": {
        "dashboard": True,
        "pos": True,
        "products": {"view": True, "add": True, "edit": True, "delete": False, "price_change": False, "stock_adjust": True},
        "inventory": {"view": True, "add": True, "edit": True, "delete": False, "transfer": True, "count": True},
        "purchases": {"view": True, "add": True, "edit": True, "delete": False, "approve": False},
        "sales": {"view": True, "add": True, "edit": True, "delete": False, "refund": True, "discount": True},
        "customers": {"view": True, "add": True, "edit": True, "delete": False, "credit": True, "blacklist": False},
        "suppliers": {"view": True, "add": True, "edit": False, "delete": False, "payments": True},
        "employees": {"view": True, "add": False, "edit": False, "delete": False, "salary": False, "attendance": True},
        "debts": {"view": True, "add": True, "edit": True, "delete": False, "collect": True},
        "expenses": {"view": True, "add": True, "edit": True, "delete": False, "approve": False},
        "repairs": {"view": True, "add": True, "edit": True, "delete": False},
        "reports": {"sales": True, "inventory": True, "financial": False, "customers": True, "employees": False, "advanced": False},
        "settings": False,
        "users": {"view": True, "add": False, "edit": False, "delete": False, "permissions": False},
        "recharge": True,
        "api_keys": False,
        "factory_reset": False,
        "woocommerce": False,
        "delivery": True,
        "loyalty": True,
        "notifications": True,
        "maintenance": False
    },
    "sales_supervisor": {
        "dashboard": True,
        "pos": True,
        "products": {"view": True, "add": False, "edit": False, "delete": False, "price_change": False, "stock_adjust": False},
        "inventory": {"view": True, "add": False, "edit": False, "delete": False, "transfer": False, "count": False},
        "purchases": {"view": False, "add": False, "edit": False, "delete": False, "approve": False},
        "sales": {"view": True, "add": True, "edit": True, "delete": False, "refund": True, "discount": True},
        "customers": {"view": True, "add": True, "edit": True, "delete": False, "credit": True, "blacklist": False},
        "suppliers": {"view": False, "add": False, "edit": False, "delete": False, "payments": False},
        "employees": {"view": False, "add": False, "edit": False, "delete": False, "salary": False, "attendance": False},
        "debts": {"view": True, "add": True, "edit": True, "delete": False, "collect": True},
        "expenses": {"view": False, "add": False, "edit": False, "delete": False, "approve": False},
        "repairs": {"view": True, "add": True, "edit": True, "delete": False},
        "reports": {"sales": True, "inventory": False, "financial": False, "customers": True, "employees": False, "advanced": False},
        "settings": False,
        "users": {"view": False, "add": False, "edit": False, "delete": False, "permissions": False},
        "recharge": True,
        "api_keys": False,
        "factory_reset": False,
        "woocommerce": False,
        "delivery": True,
        "loyalty": False,
        "notifications": True,
        "maintenance": False
    },
    "seller": {
        "dashboard": True,
        "pos": True,
        "products": {"view": True, "add": False, "edit": False, "delete": False, "price_change": False, "stock_adjust": False},
        "inventory": {"view": True, "add": False, "edit": False, "delete": False, "transfer": False, "count": False},
        "purchases": {"view": False, "add": False, "edit": False, "delete": False, "approve": False},
        "sales": {"view": True, "add": True, "edit": False, "delete": False, "refund": False, "discount": False},
        "customers": {"view": True, "add": True, "edit": False, "delete": False, "credit": False, "blacklist": False},
        "suppliers": {"view": False, "add": False, "edit": False, "delete": False, "payments": False},
        "employees": {"view": False, "add": False, "edit": False, "delete": False, "salary": False, "attendance": False},
        "debts": {"view": True, "add": False, "edit": False, "delete": False, "collect": False},
        "expenses": {"view": False, "add": False, "edit": False, "delete": False, "approve": False},
        "repairs": {"view": True, "add": True, "edit": False, "delete": False},
        "reports": {"sales": False, "inventory": False, "financial": False, "customers": False, "employees": False, "advanced": False},
        "settings": False,
        "users": {"view": False, "add": False, "edit": False, "delete": False, "permissions": False},
        "recharge": True,
        "api_keys": False,
        "factory_reset": False,
        "woocommerce": False,
        "delivery": False,
        "loyalty": False,
        "notifications": False,
        "maintenance": False
    },
    "inventory_manager": {
        "dashboard": True,
        "pos": False,
        "products": {"view": True, "add": True, "edit": True, "delete": False, "price_change": False, "stock_adjust": True},
        "inventory": {"view": True, "add": True, "edit": True, "delete": True, "transfer": True, "count": True},
        "purchases": {"view": True, "add": True, "edit": True, "delete": False, "approve": False},
        "sales": {"view": True, "add": False, "edit": False, "delete": False, "refund": False, "discount": False},
        "customers": {"view": False, "add": False, "edit": False, "delete": False, "credit": False, "blacklist": False},
        "suppliers": {"view": True, "add": True, "edit": True, "delete": False, "payments": False},
        "employees": {"view": False, "add": False, "edit": False, "delete": False, "salary": False, "attendance": False},
        "debts": {"view": False, "add": False, "edit": False, "delete": False, "collect": False},
        "expenses": {"view": False, "add": False, "edit": False, "delete": False, "approve": False},
        "repairs": {"view": True, "add": True, "edit": True, "delete": False},
        "reports": {"sales": False, "inventory": True, "financial": False, "customers": False, "employees": False, "advanced": False},
        "settings": False,
        "users": {"view": False, "add": False, "edit": False, "delete": False, "permissions": False},
        "recharge": False,
        "api_keys": False,
        "factory_reset": False,
        "woocommerce": False,
        "delivery": False,
        "loyalty": False,
        "notifications": True,
        "maintenance": True
    },
    "ecommerce_manager": {
        "dashboard": True,
        "pos": False,
        "products": {"view": True, "add": True, "edit": True, "delete": False, "price_change": True, "stock_adjust": False},
        "inventory": {"view": True, "add": False, "edit": False, "delete": False, "transfer": False, "count": False},
        "purchases": {"view": False, "add": False, "edit": False, "delete": False, "approve": False},
        "sales": {"view": True, "add": False, "edit": False, "delete": False, "refund": False, "discount": False},
        "customers": {"view": True, "add": True, "edit": True, "delete": False, "credit": False, "blacklist": False},
        "suppliers": {"view": False, "add": False, "edit": False, "delete": False, "payments": False},
        "employees": {"view": False, "add": False, "edit": False, "delete": False, "salary": False, "attendance": False},
        "debts": {"view": True, "add": False, "edit": False, "delete": False, "collect": False},
        "expenses": {"view": False, "add": False, "edit": False, "delete": False, "approve": False},
        "repairs": {"view": False, "add": False, "edit": False, "delete": False},
        "reports": {"sales": True, "inventory": True, "financial": False, "customers": True, "employees": False, "advanced": False},
        "settings": False,
        "users": {"view": False, "add": False, "edit": False, "delete": False, "permissions": False},
        "recharge": False,
        "api_keys": False,
        "factory_reset": False,
        "woocommerce": True,
        "delivery": True,
        "loyalty": True,
        "notifications": True,
        "maintenance": False
    },
    "accountant": {
        "dashboard": True,
        "pos": False,
        "products": {"view": True, "add": False, "edit": False, "delete": False, "price_change": False, "stock_adjust": False},
        "inventory": {"view": True, "add": False, "edit": False, "delete": False, "transfer": False, "count": False},
        "purchases": {"view": True, "add": False, "edit": False, "delete": False, "approve": True},
        "sales": {"view": True, "add": False, "edit": False, "delete": False, "refund": False, "discount": False},
        "customers": {"view": True, "add": False, "edit": False, "delete": False, "credit": False, "blacklist": False},
        "suppliers": {"view": True, "add": False, "edit": False, "delete": False, "payments": True},
        "employees": {"view": True, "add": False, "edit": False, "delete": False, "salary": True, "attendance": False},
        "debts": {"view": True, "add": True, "edit": True, "delete": False, "collect": True},
        "expenses": {"view": True, "add": True, "edit": True, "delete": True, "approve": True},
        "repairs": {"view": True, "add": False, "edit": False, "delete": False},
        "reports": {"sales": True, "inventory": True, "financial": True, "customers": True, "employees": True, "advanced": True},
        "settings": False,
        "users": {"view": False, "add": False, "edit": False, "delete": False, "permissions": False},
        "recharge": False,
        "api_keys": False,
        "factory_reset": False,
        "woocommerce": False,
        "delivery": False,
        "loyalty": False,
        "notifications": True,
        "maintenance": False
    },
    "user": {
        "dashboard": True,
        "pos": False,
        "products": {"view": True, "add": False, "edit": False, "delete": False, "price_change": False, "stock_adjust": False},
        "inventory": {"view": False, "add": False, "edit": False, "delete": False, "transfer": False, "count": False},
        "purchases": {"view": False, "add": False, "edit": False, "delete": False, "approve": False},
        "sales": {"view": True, "add": False, "edit": False, "delete": False, "refund": False, "discount": False},
        "customers": {"view": False, "add": False, "edit": False, "delete": False, "credit": False, "blacklist": False},
        "suppliers": {"view": False, "add": False, "edit": False, "delete": False, "payments": False},
        "employees": {"view": False, "add": False, "edit": False, "delete": False, "salary": False, "attendance": False},
        "debts": {"view": False, "add": False, "edit": False, "delete": False, "collect": False},
        "expenses": {"view": False, "add": False, "edit": False, "delete": False, "approve": False},
        "repairs": {"view": False, "add": False, "edit": False, "delete": False},
        "reports": {"sales": False, "inventory": False, "financial": False, "customers": False, "employees": False, "advanced": False},
        "settings": False,
        "users": {"view": False, "add": False, "edit": False, "delete": False, "permissions": False},
        "recharge": False,
        "api_keys": False,
        "factory_reset": False,
        "woocommerce": False,
        "delivery": False,
        "loyalty": False,
        "notifications": False,
        "maintenance": False
    }
}

# Role descriptions for UI
ROLE_DESCRIPTIONS = {
    "super_admin": {"ar": "سوبر أدمين - صلاحيات كاملة على النظام بالكامل", "fr": "Super Admin - Full system access"},
    "admin": {"ar": "مدير - صلاحيات كاملة على المتجر", "fr": "Admin - Full store access"},
    "manager": {"ar": "مشرف - إدارة العمليات اليومية", "fr": "Manager - Daily operations management"},
    "sales_supervisor": {"ar": "مشرف مبيعات - إشراف على المبيعات والعملاء", "fr": "Sales Supervisor - Sales and customer oversight"},
    "seller": {"ar": "بائع - عمليات البيع الأساسية فقط", "fr": "Seller - Basic sales operations only"},
    "inventory_manager": {"ar": "مدير مخزون - إدارة المخزون والمشتريات", "fr": "Inventory Manager - Stock and purchase management"},
    "ecommerce_manager": {"ar": "مسؤول متجر إلكتروني - إدارة المتجر الإلكتروني", "fr": "E-commerce Manager - Online store management"},
    "accountant": {"ar": "محاسب - التقارير المالية والديون والمصاريف", "fr": "Accountant - Financial reports, debts, and expenses"},
    "user": {"ar": "مستخدم - عرض فقط", "fr": "User - View only"}
}

# Permission categories for UI grouping
PERMISSION_CATEGORIES = {
    "sales_operations": {
        "ar": "عمليات المبيعات",
        "fr": "Opérations de vente",
        "permissions": ["pos", "sales", "customers", "debts"]
    },
    "inventory_operations": {
        "ar": "عمليات المخزون",
        "fr": "Opérations d'inventaire", 
        "permissions": ["products", "inventory", "purchases", "suppliers"]
    },
    "hr_operations": {
        "ar": "شؤون الموظفين",
        "fr": "Ressources humaines",
        "permissions": ["employees"]
    },
    "financial": {
        "ar": "العمليات المالية",
        "fr": "Opérations financières",
        "permissions": ["expenses", "reports"]
    },
    "system": {
        "ar": "إدارة النظام",
        "fr": "Gestion système",
        "permissions": ["settings", "users", "api_keys", "factory_reset"]
    },
    "services": {
        "ar": "الخدمات",
        "fr": "Services",
        "permissions": ["woocommerce", "delivery", "loyalty", "notifications", "maintenance", "repairs", "recharge"]
    }
}
