/**
 * Channel and status metadata — single source of truth for the E-Commerce Hub UI.
 * Keep keys in sync with backend/routes/ecom/constants.py.
 */

export const CHANNELS = {
  pos:       { labelAr: 'نقطة البيع',   icon: '🏪', color: 'bg-emerald-100 text-emerald-800 border-emerald-200' },
  shopify:   { labelAr: 'Shopify',     icon: '🛍️', color: 'bg-lime-100 text-lime-800 border-lime-200' },
  facebook:  { labelAr: 'Facebook',    icon: '📘', color: 'bg-blue-100 text-blue-800 border-blue-200' },
  instagram: { labelAr: 'Instagram',   icon: '📸', color: 'bg-pink-100 text-pink-800 border-pink-200' },
  tiktok:    { labelAr: 'TikTok',      icon: '🎵', color: 'bg-slate-200 text-slate-900 border-slate-300' },
  whatsapp:  { labelAr: 'واتساب',      icon: '💬', color: 'bg-green-100 text-green-800 border-green-200' },
  telegram:  { labelAr: 'تيليجرام',    icon: '✈️', color: 'bg-sky-100 text-sky-800 border-sky-200' },
  viber:     { labelAr: 'Viber',       icon: '🟣', color: 'bg-purple-100 text-purple-800 border-purple-200' },
  manual:    { labelAr: 'إدخال يدوي',  icon: '✍️', color: 'bg-gray-100 text-gray-800 border-gray-200' },
  // Shipping carriers (kind='shipping' on backend) — saved as integrations for credential storage
  yalidine:  { labelAr: 'يالدين (شحن)',     icon: '🚚', color: 'bg-orange-100 text-orange-800 border-orange-200', kind: 'shipping' },
  zr:        { labelAr: 'ZR Express (شحن)', icon: '🚚', color: 'bg-red-100 text-red-800 border-red-200',         kind: 'shipping' },
  maystro:   { labelAr: 'Maystro (شحن)',    icon: '🚚', color: 'bg-violet-100 text-violet-800 border-violet-200', kind: 'shipping' },
};

export const ORDER_STATUSES = {
  new:       { labelAr: 'جديد',         color: 'bg-blue-100 text-blue-800 border-blue-200',     dot: 'bg-blue-500' },
  needs_review: { labelAr: 'بحاجة لمراجعة', color: 'bg-orange-100 text-orange-800 border-orange-200', dot: 'bg-orange-500' },
  awaiting_confirmation: { labelAr: 'بانتظار تأكيد الزبون', color: 'bg-yellow-100 text-yellow-800 border-yellow-200', dot: 'bg-yellow-500' },
  confirmed: { labelAr: 'مؤكَّد',       color: 'bg-violet-100 text-violet-800 border-violet-200', dot: 'bg-violet-500' },
  packed:    { labelAr: 'محضَّر',       color: 'bg-amber-100 text-amber-800 border-amber-200',  dot: 'bg-amber-500' },
  shipped:   { labelAr: 'في الشحن',     color: 'bg-cyan-100 text-cyan-800 border-cyan-200',     dot: 'bg-cyan-500' },
  delivered: { labelAr: 'تم التسليم',   color: 'bg-emerald-100 text-emerald-800 border-emerald-200', dot: 'bg-emerald-500' },
  cancelled: { labelAr: 'ملغى',         color: 'bg-gray-100 text-gray-700 border-gray-200',     dot: 'bg-gray-400' },
  refunded:  { labelAr: 'مُستردّ',      color: 'bg-rose-100 text-rose-800 border-rose-200',     dot: 'bg-rose-500' },
};

// p167: unified full catalog (same companies as إدارة التوصيل)
export const SHIPPING_PROVIDERS = {
  mock:          { labelAr: 'وهمي (اختبار)' },
  yalidine:      { labelAr: 'ياليدين' },
  zr:            { labelAr: 'زد آر إكسبريس' },
  maystro:       { labelAr: 'مايسترو' },
  ecotrack:      { labelAr: 'إيكو تراك' },
  guepex:        { labelAr: 'قيبكس' },
  procolis:      { labelAr: 'بروكوليس' },
  noest:         { labelAr: 'نوست إكسبريس' },
  anderson:      { labelAr: 'أندرسون لوجيستيك' },
  mylers:        { labelAr: 'مايلرز' },
  ecom_delivery: { labelAr: 'إيكوم ديليفري' },
  elogistia:     { labelAr: 'إيلوجيستيا' },
  yalitec:       { labelAr: 'ياليتيك' },
  dhd:           { labelAr: 'دي إتش دي إكسبريس' },
  conexlog:      { labelAr: 'كونيكسلوغ' },
  coyote:        { labelAr: 'كويوت إكسبريس' },
  algerie_poste: { labelAr: 'بريد الجزائر' },
  // p256: full Algerian courier registry (mirrors backend services/ecom/algerian_couriers.py)
  abex          : { labelAr: 'أبيكس إكسبريس' },
  med_express   : { labelAr: 'ميد إكسبريس' },
  msm_go        : { labelAr: 'إم إس إم غو' },
  rex           : { labelAr: 'ريكس للتوصيل' },
  rb_livraison  : { labelAr: 'آر بي للتوصيل' },
  speed_delivery: { labelAr: 'سبيد ديليفري' },
  areex         : { labelAr: 'أريكس' },
  prest         : { labelAr: 'برست' },
  rocket        : { labelAr: 'روكيت ديليفري' },
  world_express : { labelAr: 'وورلد إكسبريس' },
  ba_consult    : { labelAr: 'بي أي كونسالت' },
  packers       : { labelAr: 'باكرز' },
  hr48          : { labelAr: '48 ساعة للتوصيل' },
  mono_hub      : { labelAr: 'مونو هاب' },
  golivri       : { labelAr: 'غوليفري' },
  salva         : { labelAr: 'سالفا ديليفري' },
  distazero     : { labelAr: 'ديستازيرو' },
  fret_direct   : { labelAr: 'فري دايركت' },
  zimou         : { labelAr: 'زيمو إكسبريس' },
  zinyatec      : { labelAr: 'زيناتيك' },
  tsl           : { labelAr: 'تي إس إل إكسبريس' },
  negmar        : { labelAr: 'نقمار إكسبريس' },
  ultra         : { labelAr: 'ألترا إكسبريس' },
  om_courrier   : { labelAr: 'أو إم كورييه' },
  allo_livraison: { labelAr: 'ألو ليفريزون' },
  assil         : { labelAr: 'أسيل ديليفري' },
  expedia_chrono: { labelAr: 'إكسبيديا كرونو' },
  hhd           : { labelAr: 'إتش إتش دي إكسبريس' },
  imir          : { labelAr: 'إيمير لوجيستيكس' },
  navex         : { labelAr: 'نافيكس ديليفري' },
  swift         : { labelAr: 'سويفت إكسبريس' },
  univer        : { labelAr: 'يونيفير ديليفري' },
  colireli      : { labelAr: 'كوليريلي' },
  fz_delivery   : { labelAr: 'إف زد ديليفري' },
  delivro       : { labelAr: 'ديليفرو ميل' },
  pdex          : { labelAr: 'بي دي إكس' },
  rm_express    : { labelAr: 'آر إم إكسبريس' },
  one_delivery  : { labelAr: 'ون ديليفري' },
  on_time       : { labelAr: 'أون تايم إكسبريس' },
  amana_speed   : { labelAr: 'أمانة سبيد' },
  rj360         : { labelAr: 'آر جي 360 إكسبريس' },
  rs_express    : { labelAr: 'آر إس إكسبريس' },
  vitrans       : { labelAr: 'فيترانس إكسبريس' },
  jo_express    : { labelAr: 'جو إكسبريس' },
  lynx          : { labelAr: 'لينكس إكسبريس' },
  jaguar        : { labelAr: 'جاكوار إكسبريس' },
  sbl           : { labelAr: 'إس بي إل إكسبريس' },
  samex         : { labelAr: 'ساميكس إكسبريس' },
  chrono_rex    : { labelAr: 'كرونو ريكس' },
  ovred         : { labelAr: 'أوفريد' },
  aranex        : { labelAr: 'أرانيكس إكسبريس' },
  gs_ecommerce  : { labelAr: 'جي إس إكسبريس' },
  khotwa        : { labelAr: 'خطوة إكسبريس' },
  royaume       : { labelAr: 'رويوم ديليفري' },
  ruta          : { labelAr: 'روتا إكسبريس' },
  dvd_delivery  : { labelAr: 'دي في دي ديليفري' },
  colex         : { labelAr: 'كوليكس إكسبريس' },
  easy_speed    : { labelAr: 'إيزي آند سبيد' },
  nord_ouest    : { labelAr: 'نورد ويست إكسبريس' },
  worlexpress   : { labelAr: 'وورل إكسبريس' },
  sogex         : { labelAr: 'سوجيكس' },
  other:         { labelAr: 'أخرى' },
};

// Forward state machine — must mirror STATUS_TRANSITIONS in backend constants.py
export const NEXT_STATUSES = {
  new:       ['confirmed', 'cancelled'],
  needs_review: ['confirmed', 'cancelled'],
  awaiting_confirmation: ['confirmed', 'cancelled'],
  confirmed: ['packed', 'cancelled'],
  packed:    ['shipped', 'cancelled'],
  shipped:   ['delivered', 'refunded'],
  delivered: ['refunded'],
  cancelled: [],
  refunded:  [],
};
